version: "3"
services:

  crawler:
    image: 'web-crawler'
    volumes:
     - .:/tmp
    ports:
     - '8080:8080'
    links:
     - db
#    build:
#      context: ./src/main/docker/crawler

  db:
    build:
      context: docker/db # Not sure if this is needed
    image: 'postgres:9.6'
    environment:
      - POSTGRES_DB=web_crawler
      - POSTGRES_USER=postgres
    # Ports are used for accessing the DB outside of Docker
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data