version: "3"
services:
#  crawler:
#    build:
#      context: ./src/main/docker
#    volumes:
#     - .:/tmp
  db:
    container_name: db
    image: 'postgres:9.6'
    environment:
      - POSTGRES_DB=web_crawler
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

#    This image name should be used if Dockerfile is used:
#    `docker build -t crawler/db:9.6 .`
#    image: 'crawler/db:9.6'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    # links ? to connect crawler and db
    # https://docs.docker.com/compose/compose-file/#links

